/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cbccore_low_Create */

#ifndef _Included_cbccore_low_Create
#define _Included_cbccore_low_Create
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbccore_low_Create
 * Method:    create_connect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1connect
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1disconnect
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1start
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_passive
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1passive
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_safe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1safe
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_full
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1full
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_spot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1spot
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_cover
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1cover
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_demo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1demo
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_cover_dock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1cover_1dock
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_mode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1mode(JNIEnv *, jobject, jfloat);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_lbump
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1lbump(JNIEnv *, jobject, jfloat);

/* Class:     cbccore_low_Create
 * Method:    get_create_lbump
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1lbump(JNIEnv *, jobject, jfloat);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_rbump
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1rbump(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_lwbump
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1lwbump(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_cwbump
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1cwbump(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_rwbump
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1rwbump(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_wall
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1wall(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_lcliff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1lcliff(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_rcliff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1rcliff(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_lfcliff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1lfcliff(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_rfcliff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1rfcliff(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_vwall
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1vwall(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_overcurrents
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1overcurrents(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_infrared
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1infrared(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_advance_button
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1advance_1button(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_play_button
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1play_1button(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_distance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1distance(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_normalized_angle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1normalized_1angle(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_total_angle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1total_1angle(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    set_create_normalized_angle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_set_1create_1normalized_1angle(JNIEnv *env, jobject obj, jint angle);

/*
 * Class:     cbccore_low_Create
 * Method:    set_create_total_angle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_set_1create_1total_1angle(JNIEnv *env, jobject obj, jint angle);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_battery_charging_state
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1battery_1charging_1state(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_battery_voltage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1battery_1voltage(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_battery_current
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1battery_1current(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_battery_temp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1battery_1temp(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_battery_charge
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1battery_1charge(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_battery_charge
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1battery_1capacity(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_wall_amt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1wall_1amt(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_lcliff_amt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1lcliff_1amt(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_rcliff_amt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1rcliff_1amt(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_lfcliff_amt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1lfcliff_1amt(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_rfcliff_amt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1rfcliff_1amt(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_bay_DI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1bay_1DI(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_bay_AI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1bay_1AI(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_song_number
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1song_1number(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_song_playing
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1song_1playing(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_number_of_stream_packets
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1number_1of_1stream_1packets(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_requested_velocity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1requested_1velocity(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_requested_radius
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1requested_1radius(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_requested_right_velocity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1requested_1right_1velocity(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    get_create_requested_left_velocity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_get_1create_1requested_1left_1velocity(JNIEnv *env, jobject obj, jfloat lag);

/*
 * Class:     cbccore_low_Create
 * Method:    create_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1stop
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_drive
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1drive
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_drive_straight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1drive_1straight
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_spin_CW
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1spin_1CW
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_spin_CCW
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1spin_1CCW
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_drive_direct
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1drive_1direct
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_spin_block
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1spin_1block
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_advance_led
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1advance_1led
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_play_led
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1play_1led
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_power_led
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1power_1led
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_digital_output
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1digital_1output
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_pwm_low_side_drivers
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1pwm_1low_1side_1drivers
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_low_side_drivers
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1low_1side_1drivers
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_load_song
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1load_1song
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_play_song
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1play_1song
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_read_block
 * Signature: ([CI)I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1read_1block
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_write_byte
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1write_1byte
  (JNIEnv *, jobject, jchar);

/*
 * Class:     cbccore_low_Create
 * Method:    create_clear_serial_buffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1clear_1serial_1buffer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
